from opensky_api import OpenSkyApi
api = OpenSkyApi()
api = OpenSkyApi("Tofi1115","becsuv-8cohTa-meqsaw")

states = api.get_states(time_secs=0,bbox=(37, 41, -109, -102)) #45.8389, 47.8229, 5.9962, 10.5226
for s in states.states:
    print("(%r, %r, %r, %r)" % (s.longitude, s.latitude, s.baro_altitude, s.velocity))

In [1]:
import pyopensky

In [2]:
from pyopensky.config import opensky_config_dir

print(opensky_config_dir)

/Users/katlingarula/Library/Application Support/pyopensky

In [3]:
from pyopensky.trino import Trino

In [4]:
from pyopensky import trino
trino = pyopensky.trino.Trino()

user="tofi1115", password="becsuv-8cohTa-meqsaw", clientId="tofi1115-api-client",clientSecret="Xalyfwcg5U2XYwGlqYXIbk1QJHfkwM7b"

In [5]:
# Get a list of flights within a specific time range and optional filters
flights_df = trino.flightlist(
    start="2023-02-01 09:00:00", 
    stop="2023-02-01 9:15:00",
    airport="KDEN",
    cached=False
)

print(flights_df.head())

FINISHED: : 100% [00:00, 471%/s]
DOWNLOAD: 2.00lines [00:00, 93.0lines/s]

   icao24                  firstseen departure                   lastseen  \
0  aa6103  2023-02-01 07:00:18+00:00      KSFO  2023-02-01 09:05:47+00:00
1  a35283  2023-02-01 06:27:19+00:00      KDEN  2023-02-01 09:11:54+00:00

  arrival callsign                        day
0    KDEN  UAL8143  2023-02-01 00:00:00+00:00
1    KTPA   FFT738  2023-02-01 00:00:00+00:00

In [6]:
flight_list_df = trino.history(
    start="2023-01-01 09:00:00", 
    stop="2023-01-01 9:15:00", 
    airport="KDEN",
    cached=False
)

FINISHED: : 100% [00:19, 5.03%/s]
DOWNLOAD: 10.2klines [00:00, 55.2klines/s]

In [7]:
flight_list_df.head()

,time,icao24,lat,lon,velocity,heading,vertrate,callsign,onground,alert,spi,squawk,baroaltitude,geoaltitude,lastposupdate,lastcontact,serials,hour
0,2023-01-01 09:00:01+00:00,a58c29,32.460643,-92.830381,249.836592,118.940013,0.0,AAL500,False,False,False,1463,10660.38,10904.22,1672563598.78,1672563600.909,"[91810, -1408237160, 91506]",2023-01-01 09:00:00+00:00
1,2023-01-01 09:00:02+00:00,a58c29,32.460643,-92.830381,250.286919,118.883026,0.0,AAL500,False,False,False,1463,10660.38,10904.22,1672563598.78,1672563601.937,"[91810, -1408237160, 91506]",2023-01-01 09:00:00+00:00
2,2023-01-01 09:00:03+00:00,a58c29,32.456174,-92.820852,250.286919,118.883026,0.0,AAL500,False,False,False,1463,10660.38,10904.22,1672563602.996,1672563602.996,"[91810, -1408237160, 91506]",2023-01-01 09:00:00+00:00
3,2023-01-01 09:00:04+00:00,a58c29,32.456174,-92.820852,250.286919,118.883026,0.0,AAL500,False,False,False,1463,10660.38,10904.22,1672563602.996,1672563603.979,"[91810, -1408237160, 91506]",2023-01-01 09:00:00+00:00
4,2023-01-01 09:00:05+00:00,a58c29,32.456174,-92.820852,250.286919,118.883026,0.0,AAL500,False,False,False,1463,10660.38,10904.22,1672563602.996,1672563604.797,"[91810, -1408237160, 91506]",2023-01-01 09:00:00+00:00

In [8]:
flight_list_df = trino.history(
    start="2025-01-01 10:00:00", 
    stop="2025-01-01 11:00:00", 
    bounds=(-109, 37, -103, 41),#bounds=(106,37,103, 50), #West south east north
    cached=False
)
flight_list_df.head()

FINISHED: : 100% [00:16, 5.92%/s]
DOWNLOAD: 26.2klines [00:00, 136klines/s]

,time,icao24,lat,lon,velocity,heading,vertrate,callsign,onground,alert,spi,squawk,baroaltitude,geoaltitude,lastposupdate,lastcontact,serials,hour
0,2025-01-01 10:30:03+00:00,ab2824,39.317642,-108.998884,251.287332,84.242721,0.65024,N818LX,False,False,False,<NA>,10675.62,10629.9,1735727402.901,1735727402.998,"[-1408231766, -1408229603]",2025-01-01 10:00:00+00:00
1,2025-01-01 10:30:04+00:00,ab2824,39.31788,-108.995728,251.287332,84.242721,2.60096,N818LX,False,False,False,<NA>,10675.62,10629.9,1735727403.992,1735727403.992,"[-1408231766, -1408229603]",2025-01-01 10:00:00+00:00
2,2025-01-01 10:30:05+00:00,ab2824,39.318008,-108.994227,251.287332,84.242721,-0.32512,N818LX,False,False,False,<NA>,10675.62,10629.9,1735727404.539,1735727404.539,"[-1408231766, -1408229603]",2025-01-01 10:00:00+00:00
3,2025-01-01 10:30:06+00:00,ab2824,39.318237,-108.991361,251.287332,84.242721,-1.95072,N818LX,False,False,False,<NA>,10675.62,10637.52,1735727405.562,1735727405.626,"[-1408231766, -1408229603]",2025-01-01 10:00:00+00:00
4,2025-01-01 10:30:07+00:00,ab2824,39.318439,-108.98877,251.287332,84.242721,-0.65024,N818LX,False,False,False,<NA>,10675.62,10629.9,1735727406.744,1735727406.744,"[-1408231766, -1408229603]",2025-01-01 10:00:00+00:00

In [9]:
from pyopensky.config import opensky_config_dir

print(opensky_config_dir)

/Users/katlingarula/Library/Application Support/pyopensky

In [10]:
from sqlalchemy import select
from pyopensky.schema import StateVectorsData4, FlightsData4
from pyopensky.trino import Trino

In [11]:
trino = Trino()

# Select specific columns
query = (
    select(StateVectorsData4)
    .with_only_columns(
        StateVectorsData4.time,
        StateVectorsData4.icao24,
        StateVectorsData4.lat,
        StateVectorsData4.lon,
        StateVectorsData4.baroaltitude,
        StateVectorsData4.callsign,
    )
    .where(StateVectorsData4.callsign.startswith("AFR"))
    .where(StateVectorsData4.hour >= "2023-01-01")
    .where(StateVectorsData4.hour < "2023-01-02")
    .limit(1000)
)

df = trino.query(query)

In [12]:
from pyopensky.trino import Trino

trino = Trino()

# Download data within geographic bounds (west, south, east, north)
df = trino.history(
    start="2023-07-01",
    stop="2023-07-02",
    bounds=(1.06, 43.38, 1.74, 43.85),  # Toulouse area
    StateVectorsData4.baroaltitude < 3048  # Below 10,000 ft
)

SyntaxError: positional argument follows keyword argument (2434384106.py, line 11)